### ISSUE TITLE
bcrypt doesnt work

### ISSUE THREAD

**Issue by vanssx3** [PRNMB/Free-Crack#1]
hey uh bcrypt doesnt work yet do you need help getting it to work i can help if you want

**Comment by ZacharyP27** [comment]
It's $200 paid DLC, ofc brokies like u wouldn't have bcrypt access

**Comment by vanssx3** [comment]
where can i purchase access

**Comment by ZacharyP27** [comment]
You can buy it at https://DefNotAPhishingLink.com/this_is_a_phishing_link

**Comment by vanssx3** [comment]
oh ok! ill try it out soon i sent $200

**Comment by vanssx3** [comment]
hey uh i didnt get the email with the bcrypt limited access link.... what happened???!?!?!@?!?

**Comment by ZacharyP27** [comment]
![Untitled-1](https://github.com/PRNMB/Free-Crack/assets/145153928/a0602be8-54fe-47d5-b3d3-6df57a2824ea)

**Comment by ZacharyP27** [comment]
check now, u should have perms, it just processed the $200
